<?php

/**
 * Implement hook_menu();
 */
function modal_window_views_menu()
{
  $items['edit/%ctools_js/%'] = array(
    'title' => 'Sign up',
    'page arguments' => array(1, 2),
    'page callback' => '_modal_window_callback',
    'access callback' => 'user_is_logged_in',
    'file' => 'modal_window_views.form.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}




/**
 * @param null $js
 * @param null $nid
 * a callback to implement ctools in achieve modal window
 */
function _modal_window_callback($js = NULL, $nid = NULL)
{
  global $user;

  //Include ctools if page contains nojs
  if($js)
  {
    ctools_include('modal');
    ctools_include('ajax');
    ctools_modal_add_js();
  }

  $form_state = array(
    'title' => 'Sign Up',
    'ajax' => TRUE
  );

  $form_state['values']['nid'] = $nid;
  $output = ctools_modal_form_wrapper('modal_window_views_form', $form_state);

    global $base_url;

  if (!empty($form_state['executed']))
  {
    $output = array();
    //if success, reload
    $path = $base_url. '/user/'. $user->uid .'/joined';
    var_dump($path);

    ctools_add_js('ajax-responder');
    $output[] = ctools_ajax_command_redirect($path);
  }

  print ajax_render($output);
  exit;

}
